/**
 * AUTO-GENERATED by scripts/sync-chains.ts — DO NOT EDIT.
 * Source of truth: OpenSea REST API + scripts/chain-data.json
 * Run `pnpm sync-chains` to regenerate.
 */

/** Map EVM chain IDs to Fireblocks asset IDs. */
export const CHAIN_TO_FIREBLOCKS_ASSET: Record<number, string> = {
  1: "ETH",
  10: "ETH-OPT",
  130: "UNICHAIN_ETH",
  137: "MATIC_POLYGON",
  360: "SHAPE_ETH",
  1329: "SEI_EVM",
  1868: "SONEIUM_ETH",
  2741: "ABSTRACT_ETH",
  8453: "BASECHAIN_ETH",
  33139: "APE_CHAIN",
  42161: "ETH-AETH",
  43114: "AVAX",
  80094: "BERA_CHAIN",
  81457: "BLAST_ETH",
  7777777: "ZORA_ETH",
}
